### ISSUE TITLE
Hello, can you fix the problem in Chinese?

### ISSUE THREAD

**Issue by gitzaai** [justoverclockl/hot-discussions-cards#3]
Hello, can you fix the problem of too many characters in Chinese?

![Snipaste_2023-06-30_21-12-48.jpg](https://cdnjson.com/images/2023/06/30/Snipaste_2023-06-30_21-12-48.jpg)

**Comment by justoverclockl** [comment]
can you provide an url of your website?

**Comment by gitzaai** [comment]
> can you provide an url of your website?

Hello, my website is https://forum.gitzaai.com/

**Comment by gitzaai** [comment]
[[kai](https://www.subarist.net/)]  told me to fix it by adding the following code 

less/css

```css
.card p {
     line-height: 1.5em;
    font-size: 14px;
    overflow: hidden;
    display: -webkit-box;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 3;
    padding-top: 3px;
}
```
